// Generated by scripts/build-rules.mjs. Do not edit.
import r0 from './psychic.json' with { type: 'json' };
import r1 from './destiny.json' with { type: 'json' };
import r2 from './master.json' with { type: 'json' };
import r3 from './personality.json' with { type: 'json' };
import r4 from './missing.json' with { type: 'json' };
import r5 from './planes.json' with { type: 'json' };
import r6 from './repeats.json' with { type: 'json' };
import r7 from './karmic.json' with { type: 'json' };
import r8 from './pairs.json' with { type: 'json' };
import r9 from './maturity.json' with { type: 'json' };
import r10 from './name.json' with { type: 'json' };
import r11 from './first-letter.json' with { type: 'json' };
import r12 from './present.json' with { type: 'json' };
import r13 from './watch.json' with { type: 'json' };
export const RULES = [...r0.rules, ...r1.rules, ...r2.rules, ...r3.rules, ...r4.rules, ...r5.rules, ...r6.rules, ...r7.rules, ...r8.rules, ...r9.rules, ...r10.rules, ...r11.rules, ...r12.rules, ...r13.rules];
