// Builds the owner's review page (review/index.html) and RULEBOOK_REVIEW.md from the rule files and the engine,
// so the page always shows exactly what the site will run. Run: npm run review
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { baseRulebook } from '../engine/rulebook.js';
import { polarity } from '../engine/core.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = p => readFileSync(join(root, p), 'utf8');

// The engine is an ES module; in the page it runs as a plain script inside a function scope.
const engineSource = read('engine/core.js').replace(/^export /gm, '');
const safeJson = JSON.stringify(baseRulebook).replace(/</g, '\\u003c');
const html = read('review/template.html')
  .replace('/*__RULEBOOK__*/null', () => safeJson)
  .replace('/*__ENGINE__*/', () => engineSource);
writeFileSync(join(root, 'review/index.html'), html);

// Plain-text record of the rulebook for the repository.
const B = baseRulebook;
const cell = s => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const story = s => [s.good && `Good: ${s.good}`, s.trait && `Trait: ${s.trait}`, s.care && `Care: ${s.care}`].filter(Boolean).join(' <br> ');
const md = [];
md.push('# Rulebook review', '', 'Generated by `npm run review` from `rules/`. Every quote below was checked word for word against `sources/` by `npm run lint:rules`.', '');
md.push('Owner sign-off happens on the review page (`review/index.html`, published as a private artifact). Decisions are copied into `rules/review.json`.', '');
md.push('## Calculation method', '');
for (const s of B.method.steps) md.push(`- **${s.id}**${s.confirm ? ' (needs owner confirmation)' : ''}: ${s.text}`);
md.push('', `Chaldean table: ${Object.entries(B.method.chaldean).map(([n, l]) => `${n} = ${l}`).join(' · ')}`, '');
md.push('## Conflicts between sources', '');
for (const c of B.conflicts.conflicts) md.push(`- **${c.id}**: ${c.topic} Options: ${c.options.map(o => o.label).join(' / ')}. Decision: ${c.decision ?? 'not decided'}`);
md.push('', `## Shot-gun pairs (${B.shotgun.rules.length})`, '', '| Rule | Pair | Source (P01) | Site wording | Grade |', '|---|---|---|---|---|');
for (const r of B.shotgun.rules) md.push(`| ${r.id} | ${r.ordered ? `${r.pair[0]}→${r.pair[1]}` : `${r.pair[0]}-${r.pair[1]}`} | ${cell(`${r.ref}: ${r.quote}`)} | ${cell(story(r.story))} | ${polarity(r.story)} |`);
md.push('', `## Grid yogas (${B.yogas.rules.length})`, '', '| Rule | Name | Present / absent | Source (P01) | Site wording | Grade |', '|---|---|---|---|---|---|');
for (const r of B.yogas.rules) md.push(`| ${r.id} | ${cell(r.name)} | ${r.present.join(',')} / ${r.absent.join(',') || '–'} | ${cell(`${r.ref}: ${r.quote}`)} | ${cell(story(r.story))} | ${polarity(r.story)} |`);
md.push('', '## Digits & planets', '', '| Rule | Digit | Site wording |', '|---|---|---|');
for (const r of B.planets.rules) md.push(`| ${r.id} | ${r.digit} ${r.planet} | ${cell(r.story.trait)} Signifies: ${cell(r.story.signifies)} |`);
md.push('', '## Professions', '', '| Rule | Field | Codes |', '|---|---|---|');
for (const r of B.professions.rules) md.push(`| ${r.id} | ${cell(r.field)} | ${r.codes.join(' / ')} |`);
md.push('', '## Remedies by birth number', '', '| Rule | Birth no. | Screen saver | Bracelet | Mani |', '|---|---|---|---|---|');
for (const r of B.remedies.rules) md.push(`| ${r.id} | ${r.birth_number} | ${cell(r.screen_saver_from === 'destiny' ? `Destiny number's screen saver${r.screen_saver ? `, or ${r.screen_saver}` : ''}` : r.screen_saver)} | ${cell(r.bracelet)} | ${cell(r.mani)} |`);
for (let y = 1; y <= 9; y++) {
  md.push('', `## Personal year ${y}`, '', '| Rule | Topic | Source quote | Site wording |', '|---|---|---|---|');
  for (const it of B.personalYear.years[y]) md.push(`| ${it.id} | ${it.cat}${it.conflict ? ` (${it.conflict})` : ''} | ${cell(`${it.src}: ${it.quote}`)} | ${cell(it.text)} |`);
}
md.push('', '## For every year', '');
for (const it of B.personalYear.for_everyone) md.push(`- **${it.id}** (${it.src}): ${it.text}`);
writeFileSync(join(root, 'RULEBOOK_REVIEW.md'), md.join('\n') + '\n');

console.log(`Wrote review/index.html (${Math.round(html.length / 1024)} KB) and RULEBOOK_REVIEW.md`);
